server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.19:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 813929MySQL

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
